### ISSUE TITLE
[fix] docker compose

### ISSUE THREAD

**Issue by koreanddinghwan** [42-pingpong/backend#131]
## 문제

1. client가 브라우저에 접속한 상황에서
2. restapi 서버가 아닌, socket 서버가 먼저 올라가면
3. socket server에서 connection refused되며 서버가 죽은 케이스가 발생.

<br>

## 해결

docker compose에서 healthcheck통해 해결할 예정

**Comment by koreanddinghwan** [comment]
docker compose 순서 강제화

```yaml
  restapis:
    container_name: restapis
    build:
      context: .
      dockerfile: apps/restapis/Dockerfile
    env_file:
      - apps/restapis/.env.dev
    working_dir: /app
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '10002:10002'
    depends_on:
      - docdb
      - rdb
    networks:
      - intra
    healthcheck:
      test: ["CMD", "curl", "-f", "http://restapis:10002/api"]
      interval: "5s"
      timeout: "1s"
      retries: 20
      start_period: "10s"
```

```yaml
  sockets:
    container_name: sockets
    build:
      context: .
      dockerfile: apps/sockets/Dockerfile
    env_file:
      - apps/sockets/.env.dev
    working_dir: /app
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '10001:10001'
    depends_on:
      docdb:
        condition: service_started
      rdb:
        condition: service_started
      restapis:
        condition: service_healthy
    networks:
      - intra
```

socket 서버가 restapis 서버의 healthcheck가 완료된 후에 컨테이너에 올라가도록 변경함.
